function portfolio_defaultSettings( portfolio )
portfolio_settings(portfolio,'portfolioMetricsMode','portfolio',...
    'windowLength', '1d',...
    'holdingPeriodsOnly', 'false',...
    'shortSalesMode', 'lintner',...
    'jumpsModel', 'moments',...
    'noiseModel', 'true',...
    'fractalPriceModel','true',...
    'factorModel', 'sim',...
    'densityModel','GLD',...
    'driftTerm','false',...
    'resultsNAFilter', 'true',...
    'resultsSamplingInterval', '1s',...
    'inputSamplingInterval','1s',...
    'timeScale','1d',...
    'txnCostPerShare',0,...
    'txnCostFixed',0)
end